#!/data/data/com.termux/files/usr/bin/bash

### install dependencies 
pkg install root-repo x11-repo axel bsdtar proot neofetch pulseaudio -y

### Ascii
neofetch --ascii_distro Archlinux -L

### Download Tarball
axel -a --search -o archlinux-arm64.tar.xz https://fl.us.mirror.archlinuxarm.org/os/ArchLinuxARM-aarch64-latest.tar.gz

### Decompressed tarball
echo "Decompressing Rootfs...!!!"
proot --link2symlink bsdtar -xpJf archlinux-arm64.tar.xz 2>/dev/null

### Make executable bin
wget -O $PREFIX/bin/archlinux https://raw.githubusercontent.com/xiv3r/Archlinux-Termux/refs/heads/main/archlinux/archlinux

### Fix shebang
termux-fix-shebang $PREFIX/bin/archlinux
chmod 700 $PREFIX/bin/archlinux
archlinux
